name: GamesMaster
version: 1.4.6
description: A plugin to make your games world become almost like a complete minigames server!
author: Jeremaster101
main: GamesMaster
depend: [WorldEdit]
api-version: 1.13
commands:
  gamesmaster:
    description: Main GamesMaster command. Type '/gamesmaster help' for help.
    usage: /<command>